### ISSUE TITLE
Fold this back into Embark?

### ISSUE THREAD

**Issue by minad** [karthink/elmo#1]
Hey @karthink,

would it make sense to merge this back into Embark, or at least parts of it? I am missing an embark-completions-mode from Embark. As I understand, @oantolin didn't add such a mode so far since there are multiple ways to setup the embark-completions mode and for each way a slightly different setup is required. Elmo looks as if it goes in the right direction. There is an elmo-mode (~ embark-completions-mode) and there is a bunch of customization variables which tweak the mode.

**Comment by oantolin** [comment]
We should also consider the other way around: leave just `embark-collect-snapshot` in Embark and move all the completions stuff out of Embark.

**Comment by minad** [comment]
@oantolin Yes, this could also be a good idea. I am all for splitting up packages if reasonable cutting points can be found.

**Comment by karthink** [comment]
I think this is @oantolin's call. I'm okay with any of the suggested approaches, but here are a couple of things to note either way:

1. Elmo is slow, as we've discussed before in [#101](https://github.com/oantolin/embark/issues/101). I've set it to not show completions until a minimum number of chars are typed (similar to Prot's mct.el), as well as a debounce/delay when updating. I prefer the former and live with the latter, but both delays are almost necessary to use Embark live completions without stuttering. I don't know if anyone else will be interested in Embark live completions as an incremental completion system given these limitations. (I understand that I'm fitting a square peg into a round hole with Elmo, but the biggest win either way would be speeding up updates to the live-collect buffer.)

2. Currently my personal preferences for keybindings and buffer display are baked into elmo.el. I can remove these and use more sane defaults if the plan is to make this an actual package (independently or as part of Embark).

Some thoughts on the two options:

### Fold `elmo-mode` into Embark and rename it to `embark-live-mode` or `embark-completions-mode`. 

- The code will shrink by about a third in size since I aliased, renamed or redefined a few Embark functions/variables and these won't be necessary.
- Like you, I prefer orthogonal + composable code too, and this does seem like a move in the opposite direction for Embark. That said, deciding what "composable" means here probably requires intimate familiarity with the code. For example, `embark-prefix-help-command` seemed out of place in Embark (as a feature) but I learnt that it was a very cheap addition to Embark (in terms of complexity) because of how it reuses the completing-read-prompter code. So I defer to @oantolin here.
- If we go this route, I can submit a PR to Embark and will archive this repo with a note. It will be a couple of weeks before I can work on this though.

### Excise Embark's live collect feature and combine it with Elmo to make Embark-Live, a new package

The name is tentative. (Although Elmo has a nice ring to it.)

- Are there users who use Embark live collect without also using it as a pseudo-completion system? These folks will be inconvenienced by having to install Embark-Live, a full incremental-completion framework, just to access live collect buffers again.
- If we go this route, I can work on adding the completion UI stuff from Elmo to Embark-Live after the intial commit, and can help with maintaining the package afterwards. I'm not familiar enough with Embark for the initial extraction though.

**Comment by minad** [comment]
1. As I see it the slowness is fundamentally not fixable, since if you want a buffer with all the candidates (which can be isearched for example), you necessarily have to print all of them. This is different from keyhole UIs like Vertico, which only show a small subset. I probably already said something like this in #101.
 
2. I don't have a strong preference about the defaults as long as the main settings can be adjusted. Embark already comes with some non-reasonable defaults, e.g, the in your face indicator and embark-quit-after-action=t ;)

3. From the perspective of the package ecosystem it may look better if the elmo/embark-live package is kept separate. The main selling point is to have these decoupled components, if Embark comes with more and more completion features of its own, we somehow lose that and Embark may start to look more and more like Helm 2.0. Then there are more reasons for a separate package. I think new users are already overwhelmed a bit with the Embark functionality. Also having a separate package allows for more experimentation without affecting existing functionality. This point should not be underestimated - for example I find it very satisfying that packages like Marginalia or Orderless feel like *done*, they are good as is. This was only possible since these packages have well defined bounds. On the other hand I am not sure if the extraction can be made in a reasonable way or if one would just end up with a lot of internal Embark API use and messy details. Therefore I initially asked here if merging back would make sense. But I would be okay to lose the embark-live-collect feature, or I would use elmo for that then. So as you suggest maybe all the live code could be cut out and Embark would not offer much more than an API to refresh the existing collect buffer to enable live updates.

**Comment by minad** [comment]
Now that the completion feature has been removed from Embark we can close this. A new Embark-based completion system should live outside Embark, inside the Elmo package, such that Embark stays more focused on its core values.
